HW2
BertaFly/IL-FE-course-HW1 pull request #3
Opened 2017-03-01 11:55 UTC by BertaFly

Please check my second task.
Used float and inline-block display. Didn't want to use flex (due to low brouser support), table (to complicated).

2017-03-01 19:25 UTC, UnknownKira requested changes

2017-03-01 19:25 UTC, UnknownKira commented on Documents/Серьезно/Работа/Програмирование/Илья курс/гит/HW2/index.html
> +			<nav class="menu-top">
когда наводишь на элементы верхнего меню, появляются лишние границы и двигают соседние элементы, так не должно быть

2017-03-01 19:25 UTC, UnknownKira commented on Documents/Серьезно/Работа/Програмирование/Илья курс/гит/HW2/index.html
> +			<nav class="menu-top">
слишком большие размеры, картинка и верхнее меню явно не соответствуют масштабу макета

2017-03-01 19:29 UTC, egemon commented
Global flex-box browser support
82.91%	+	14.6%	=	97.5%
Checkout: http://caniuse.com/#search=flex

2017-03-02 13:53 UTC, BertaFly commented on Documents/Серьезно/Работа/Програмирование/Илья курс/гит/HW2/index.html
> +			<nav class="menu-top">
done

2017-03-02 14:19 UTC, UnknownKira reviewed
хмм, ну я не уверен что ты правильно сделала, но и не могу сказать что не правильно, мне интересно что скажет на это Илья

2017-03-02 16:39 UTC, UnknownKira approved these changes

2017-03-05 22:40 UTC, closed without merging